[package]
name = "sibs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.8"
futures-lite = "2.2.0"
indicatif = "0.17.7"
regex = "1.10.3"
terminal_size = "0.3.0"
thiserror = "1.0.50"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "process", "sync", "macros"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7", features = ["codec"] }
importer = { path = "./importer" }

[dev-dependencies]
proptest = "1.4.0"
lazy_static = "1.4.0"
