[package]
name = "sibs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.1.1"
async-process = "2.0.1"
async-std = "1.12.0"
console = "0.15.8"
futures-lite = "2.2.0"
indicatif = "0.17.7"
terminal_size = "0.3.0"
thiserror = "1.0.50"
