[package]
name = "sibs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.1.1"
async-io = "2.3.0"
async-process = "2.0.1"
console = "0.15.8"
futures-lite = "2.2.0"
indicatif = "0.17.7"
regex = "1.10.3"
terminal_size = "0.3.0"
thiserror = "1.0.50"

[dependencies.async-std]
version = "1.12.0"
features = [
    "attributes",
]

[dev-dependencies]
proptest = "1.4.0"
