[workspace]
resolver = "2"
members = [
    "engine/lexer",
    "engine/asttree",
    "engine/parser",
    "engine/diagnostics",
    "engine/semantic",
    "engine/interpreter",
    "engine/common",
    "engine/runtime",
    "engine/functions",
    "engine/driver",
    "engine/support/boxed",
    "engine/support/docs",
    "engine/support/importer",
    "engine/support/term",
    "engine/tests/cmds/test_utils",
    "engine/tests/cmds/exit",
    "engine/tests/cmds/noise",
    "app/cli",
    "app/lsp",
    "app/scenario",
]

[workspace.dependencies]
enum_ids           = "0.7"
thiserror          = "2.0"
uuid               = "1.16"
proptest           = "1.4"
paste              = "1.0"
syn                = "2.0"
quote              = "1.0"
proc-macro2        = "1.0"
tokio-util         = "0.7"
tokio              = "1.44"
tokio-stream       = "0.1"
tower-lsp          = "0.20"
tracing            = "0.1"
tracing-subscriber = "0.3"
tracing-appender   = "0.2"
console            = "0.16"
indicatif          = "0.18"
indexmap           = "2.7"
rand               = "0.9"
futures            = "0.3"
bstorage           = "0.2"
fshasher           = "0.3"
serde              = "1.0"
blake3             = "1.4"
terminal_size      = "0.4"
regex              = "1.10"
brec               = "0.6"
chrono             = "0.4"
