use crate::*;

test_node_grammar!(
    envs_body_grammar,
    EnvsModule::read_as_linked,
    accepts = [
        "",
        "// comment\n",
        "required ENV_A; optional ENV_B;",
        "optional ENV_A; required ENV_B;",
        "// header\nrequired ENV_A;\n// tail\n",
        "optional ENV_A;\n// comment\nrequired ENV_B;",
        "required\nENV_A; optional\nENV_B;",
    ],
    rejects = [
        "required ENV_A: str;",
        "optional ENV_A: str;",
        "required ENV_A = \"x\";",
        "optional ENV_A = \"x\";",
        "let ENV_A;",
        "required ENV_A.foo();",
        "optional ENV_A[0];",
        "required optional ENV_A;",
        "optional required ENV_A;",
        "required required ENV_A;",
        "optional optional ENV_A;",
        "required \"ENV_A\";",
        "optional 123;",
    ],
    errors = [
        "ENV_A;" => E::MissedEnvRequirement,
        "ENV_A" => E::MissedEnvRequirement,
        "// comment\nENV_A;" => E::MissedEnvRequirement,
        "required ENV_A; ENV_B;" => E::MissedEnvRequirement,
        "optional ENV_A; ENV_B;" => E::MissedEnvRequirement,
        "required" => E::MissedEnvName,
        "optional" => E::MissedEnvName,
        "required;" => E::MissedEnvName,
        "optional;" => E::MissedEnvName,
        "required ENV_A" => E::MissedSemicolon,
        "optional ENV_A" => E::MissedSemicolon,
        "required ENV_A optional ENV_B;" => E::MissedSemicolon,
    ],
);
